# 此文件相当简单
# 1. 检测到main分支有提交触发jobs任务/手动触发
# 2. 指定一个github服务器的环境ubuntu-latest
# 3. 执行pull当前的代码到github服务器
# 4. 登录docker, 并制作镜像(所有安装依赖等都写在dockerfile中, 不在此执行), 上传镜像到dockerhub和本地镜像仓库
# 5. 连接远程服务器, 停止/删除容器, 拉取本地最新镜像, 调整镜像名称, 删除本地镜像, 启动容器

name: CI/CD
on:
  push:
    branches:
      - main # 触发条件为 push main分支
jobs:
  docker: # 描述词, 无实际意义
    runs-on: ubuntu-latest # 运行的环境
    # 步骤
    steps:
      - uses: actions/checkout@v2 # 相当于执行git pull操作，以获取最新的代码

      - name: 打包镜像, 上传 Docker Hub # 描述词, 无实际意义
        run: | # 提交到dockerhub仓库和本地镜像仓库
          docker login -u luode0320 -p ${{ secrets.REGISTRY_PASSWORD }}
          docker build -t luode0320/web-start:latest .
          docker push luode0320/web-start:latest

      - name: 登录服务器, 启动 # 描述词, 无实际意义

        uses: appleboy/ssh-action@master # 通过SSH登录到远程服务器
        with: # 配置actions/setup-node@v1的一些属性
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          script: | # 远程服务器依次执行下面的命令, 删除容器, 删除镜像, 启动容器
            docker rm -f web
            docker rmi luode0320/web-start:latest
            docker run -d \
            --restart=always \
            --name web \
            -p 2000:2000 \
            luode0320/web-start:latest
